import { createBlockedDate } from './blockedDatesService';
import { logger } from '../utils/logger';

/**
 * Automatically blocks dates when a reservation is confirmed
 * @param {Object} reservation - The reservation object
 * @returns {Promise<string|null>} - Returns the blocked date ID or null if error
 */
export const blockDatesForReservation = async (reservation) => {
  try {
    logger.info('Blocking dates for reservation:', reservation.reservationCode);

    const blockData = {
      startDate: reservation.checkInDate instanceof Date 
        ? reservation.checkInDate 
        : reservation.checkInDate.toDate(),
      endDate: reservation.checkOutDate instanceof Date
        ? reservation.checkOutDate
        : reservation.checkOutDate.toDate(),
      reason: `Reserva confirmada: ${reservation.reservationCode}`,
      reservationId: reservation.id,
      autoGenerated: true,
    };

    const blockId = await createBlockedDate(blockData);
    logger.info('Dates blocked successfully:', blockId);
    
    return blockId;
  } catch (error) {
    logger.error('Error blocking dates for reservation:', error);
    throw error;
  }
};

/**
 * Checks if a date range should be automatically blocked
 * @param {string} reservationStatus - The new reservation status
 * @param {string} oldStatus - The old reservation status
 * @returns {boolean} - Whether dates should be blocked
 */
export const shouldBlockDates = (reservationStatus, oldStatus) => {
  // Block dates when moving to confirmed status from pending
  return reservationStatus === 'confirmed' && oldStatus === 'pending';
};

/**
 * Checks if dates should be unblocked
 * @param {string} reservationStatus - The new reservation status
 * @param {string} oldStatus - The old reservation status
 * @returns {boolean} - Whether dates should be unblocked
 */
export const shouldUnblockDates = (reservationStatus, oldStatus) => {
  // Unblock dates when cancelling a confirmed reservation
  return (reservationStatus === 'cancelled' || reservationStatus === 'pending') && 
         oldStatus === 'confirmed';
};
